name: Release
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Release GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: git setting
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.NAME }}
      - name: Commit files
        run: |
          git add .
          git commit -m "Build"
          git push
      - name: Push subtree
        run: |
          git remote add github "https://$NAME:$TOKEN@github.com/dev-yakuza-example/todo"
          git subtree pull --prefix build/ github gh-pages
          git subtree push --prefix build/ github gh-pages
